name: Improved Theme Settings
type: module
description: Makes the theme pages a bit UI friendly for people with the permissions.
core: 8.x
package: Custom

# Information added by Drupal.org packaging script on 2021-01-27
version: '8.x-9.8'
project: 'social'
datestamp: 1611750464
